#!/bin/bash
#
# rpi-image-tool
#
# Copyright 2017, Mike Ray, <mike.ray@btinternet.com>
#
# This is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free
# Software Foundation; either version 3, or (at your option) any later
# version.
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this package; see the file COPYING.  If not, write to the Free
# Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.
#
#--code--

export TEXTDOMAIN=rpi-image-tool
export TEXTDOMAINDIR=/usr/local/share/locale

. gettext.sh

. rpi-image-tool.lib


usage() {
	USAGE=$(gettext "tool_usage")
	echo -e "${USAGE}"
}


#-- Main code

if ! check_root ; then
	PROGNAME=$0
	echo $(eval_gettext "Script must be run as root, try: sudo \$PROGNAME") ; echo
	exit 1
fi


WORKDIR=
IMAGEFILE=
FUNCTION=
SPLIT=64
BLOCKSIZE=1M
BLOCKCOUNT=

BOOTMOUNTPOINT=boot
ROOTMOUNTPOINT=root


while getopts ':C:D:F:I:M:N:c:hs:w:z:' flag ; do
	case $flag in
	h)
		usage
		exit 0
	;;
C)
		FUNCTION=cleanup
		WORKDIR=${OPTARG}
		break 2
	;;
	D)
		FUNCTION=mountdevice
		DEVICE=${OPTARG}
	;;
	F)
		FUNCTION=fixpartuuids
		WORKDIR=${OPTARG}
		break 2
	;;
	I)
		FUNCTION=installresize
		WORKDIR=${OPTARG}
		break 2
	;;
	M)
		FUNCTION=mountimage
		IMAGEFILE=${OPTARG}
	;;
	N)
		FUNCTION=new
		IMAGEFILE=${OPTARG}
	;;
	c)
		BLOCKCOUNT=${OPTARG}
		validate_blockcount ${BLOCKCOUNT}
	;;
	s)
		SPLIT=${OPTARG}
		validate_split ${SPLIT}
	;;
	w)
		WORKDIR=${OPTARG}
	;;
	z)
		BLOCKSIZE=${OPTARG}
		validate_blocksize ${BLOCKSIZE}
	;;
	(?)
		echo $(gettext "Invalid option") >&2
		echo >&2
		usage
		exit 1
	;;
	:)
		echo $(eval_gettext "Option - \$OPTARG requires an argument.") >&2
		echo >&2
		usage
		exit 1
	;;
	esac
done

[ -z ${WORKDIR} ] && { echo $(gettext "Work directory not set") ; echo ; usage; exit 1 ; }

if [ ${FUNCTION} = 'mountimage' ] || [ $FUNCTION = 'new' ]; then
	[ -z "${IMAGEFILE}" ] && { echo $(gettext "Image file name not set") ; echo ; usage; exit 1 ; }
fi

if [ ${FUNCTION} = 'mountdevice' ]; then
	[ -z "${DEVICE}" ] && { echo $(gettext "Device name not set") ; echo ; usage ; exit 1 ; }
fi

if [ ${FUNCTION} = 'new' ]; then
	[ -z ${BLOCKCOUNT} ] && { echo $(gettext "Block count not set") ; echo ; usage ; exit 1 ; }
	[ -z ${BLOCKSIZE} ] && { echo $(gettext "Block size not set") ; echo ; usage ; exit 1 ; }
	[ -z ${SPLIT} ] && { echo $(gettext "Split size not set") ; echo ; usage ; exit 1 ; }
fi

case ${FUNCTION} in
	cleanup)
		clean_up ${WORKDIR}
	;;
	fixpartuuids)
		fix_partuuids ${WORKDIR}
	;;
	installresize)
		install_init_resize_script ${WORKDIR} /usr/lib/raspi-config/init_resize.sh
	;;
	mountimage)
		mount_image ${WORKDIR} ${IMAGEFILE} ${BOOTMOUNTPOINT} ${ROOTMOUNTPOINT}
	;;
	mountdevice)
		mount_device ${WORKDIR} ${DEVICE} ${BOOTMOUNTPOINT} ${ROOTMOUNTPOINT}
	;;
	new)
		new_image ${WORKDIR} ${IMAGEFILE} ${BOOTMOUNTPOINT} ${ROOTMOUNTPOINT} ${BLOCKCOUNT} ${BLOCKSIZE} ${SPLIT}
	;;
esac

exit 0


